apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "products-service.fullname" . }}
  labels:
    {{- include "products-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "products-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "products-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "products-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.secrets.enabled }}
            {{- range $key, $value := .Values.secrets.data }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secrets.secretName }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
