name: "CI/CD (Release)"

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  ci-cd:
    name: CI/CD
    uses: unir-tfm-devops/reusable-github-actions/.github/workflows/ci-cd-release.yml@main
    with:
      image-repo-name: "products-service"
      app-name: "products-service"
    secrets: inherit
